# Generated by Django 5.1.7 on 2025-04-08 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "department_data_migration"),
    ]

    operations = []
