# Generated by Django 5.1.7 on 2025-04-08 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0001_add_department_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["code"]},
        ),
        migrations.AddField(
            model_name="course",
            name="credits",
            field=models.IntegerField(
                default=3, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
