# Generated by Django 5.1.7 on 2025-04-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0002_alter_course_options_course_credits_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timetable",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="timetable",
            name="departments",
            field=models.ManyToManyField(
                related_name="timetables", to="exams.department"
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
