# Generated by Django 5.1.7 on 2025-04-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0003_alter_timetable_options_timetable_departments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="year",
            field=models.CharField(
                choices=[
                    ("1", "First Year"),
                    ("2", "Second Year"),
                    ("3", "Third Year"),
                    ("4", "Fourth Year"),
                ],
                default="1",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="courses",
            field=models.ManyToManyField(related_name="timetables", to="exams.course"),
        ),
        migrations.AddField(
            model_name="timetable",
            name="year",
            field=models.CharField(
                choices=[
                    ("1", "First Year"),
                    ("2", "Second Year"),
                    ("3", "Third Year"),
                    ("4", "Fourth Year"),
                ],
                default="1",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
