# Generated by Django 5.1.7 on 2025-04-08 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('exams', '0005_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.classroom'),
        ),
    ] 