# Generated by Django 5.1.7 on 2025-04-09 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0002_alter_course_options_course_credits_and_more"),
        ("exams", "0007_fix_classroom_model"),
    ]

    operations = []
