# Generated by Django 5.1.7 on 2025-04-13 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0007_add_examhall_fields"),
        ("exams", "0008_merge_20250409_2142"),
    ]

    operations = []
