# Generated by Django 5.1.7 on 2025-04-13 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0009_merge_20250413_1921"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="coordinates",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="student",
            name="hostel_block",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="room_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="examhall",
            name="coordinates",
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name="Invigilator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("employee_id", models.CharField(max_length=20, unique=True)),
                ("max_hours_per_day", models.IntegerField(default=6)),
                ("availability", models.JSONField(default=dict)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exams.department",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exam",
            name="invigilators",
            field=models.ManyToManyField(related_name="exams", to="exams.invigilator"),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("present", models.BooleanField(default=False)),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="exams.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exams.student"
                    ),
                ),
            ],
            options={
                "unique_together": {("exam", "student")},
            },
        ),
        migrations.CreateModel(
            name="SeatAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.CharField(max_length=10)),
                ("row", models.IntegerField()),
                ("column", models.IntegerField()),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_allocations",
                        to="exams.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exams.student"
                    ),
                ),
            ],
            options={
                "unique_together": {("exam", "student")},
            },
        ),
    ]
