from django.urls import path
from . import views

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('home/', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('timetable/new/', views.timetable_form, name='timetable_form'),
    path('timetable/create/', views.create_timetable, name='create_timetable'),
    path('timetable/<int:timetable_id>/', views.view_timetable, name='view_timetable'),
    path('timetable/<int:timetable_id>/export/', views.export_timetable, name='export_timetable'),
    path('timetable/<int:timetable_id>/subjects/', views.subject_schedule, name='subject_schedule'),
    path('timetable/<int:timetable_id>/schedule/', views.manual_scheduling, name='manual_scheduling'),
    path('exam/<int:exam_id>/delete/', views.delete_exam, name='delete_exam'),
    path('timetable/<int:timetable_id>/day/<str:date>/', views.day_schedule, name='day_schedule'),
    path('timetable/<int:timetable_id>/batch/', views.batch_scheduling, name='batch_scheduling'),
    path('timetable/<int:timetable_id>/subject-pairs/', views.subject_pair_scheduling, name='subject_pair_scheduling'),
    path('timetable/subject-pairs-new/', views.subject_pair_generator, name='subject_pair_generator'),
    path('timetable/subject-pairs-create/', views.create_subject_pair_timetable, name='create_subject_pair_timetable'),
    path('timetable/<int:timetable_id>/delete/', views.delete_timetable, name='delete_timetable'),
    path('timetable/<int:timetable_id>/department/', views.department_timetable, name='department_timetable'),
    path('timetable/<int:timetable_id>/semester/', views.semester_timetable, name='semester_timetable'),
    path('timetable/<int:timetable_id>/semester/pdf/', views.export_grid_pdf, name='export_grid_pdf'),
    path('subjects/', views.manage_subjects, name='manage_subjects'),
    path('classrooms/', views.manage_classrooms, name='manage_classrooms'),
    path('halls/', views.manage_halls, name='manage_halls'),
    
    # New URLs for additional features
    path('exam/<int:exam_id>/allocate-seats/', views.allocate_seats, name='allocate_seats'),
    path('exam/<int:exam_id>/add-student/', views.add_student_to_exam, name='add_student_to_exam'),
    path('exam/<int:exam_id>/import-students/', views.import_students, name='import_students'),
    path('exam/<int:exam_id>/remove-student/<int:student_id>/', views.remove_student_from_exam, name='remove_student_from_exam'),
    path('download-student-template/', views.download_template, name='download_template'),
    path('timetable/<int:timetable_id>/assign-invigilators/', views.assign_invigilators, name='assign_invigilators'),
    path('timetable/<int:timetable_id>/manual-assign-invigilators/', views.manual_assign_invigilators, name='manual_assign_invigilators'),
    path('timetable/<int:timetable_id>/add-invigilator/', views.add_invigilator, name='add_invigilator'),
    path('timetable/<int:timetable_id>/delete-invigilator/<int:invigilator_id>/', views.delete_invigilator, name='delete_invigilator'),
    path('timetable/<int:timetable_id>/edit-invigilator/<int:invigilator_id>/', views.edit_invigilator, name='edit_invigilator'),
    path('timetable/<int:timetable_id>/download-invigilator-assignments/', views.download_invigilator_assignments, name='download_invigilator_assignments'),
    path('exam/<int:exam_id>/seat-heatmap/', views.view_seat_heatmap, name='seat_heatmap'),
    path('exam/<int:exam_id>/seat-heatmap/download/', views.download_seat_heatmap, name='download_seat_heatmap'),
    path('exam/<int:exam_id>/seat-heatmap/delete/<int:row>/<int:col>/', views.delete_seat_from_heatmap, name='delete_seat_from_heatmap'),
    path('exam/<int:exam_id>/mark-attendance/', views.mark_attendance, name='mark_attendance'),
    path('exam/<int:exam_id>/attendance/download/', views.download_attendance, name='download_attendance'),
    path('select-exam/', views.select_exam, name='select_exam'),
    path('select-timetable/', views.select_timetable, name='select_timetable'),
    path('exam/<int:exam_id>/student/<int:student_id>/edit/', views.edit_student_allocation, name='edit_student_allocation'),
    path('exam/<int:exam_id>/student/<int:student_id>/delete/', views.delete_student_allocation, name='delete_student_allocation'),
    path('manage-students/', views.manage_students, name='manage_students'),
    path('student/<int:student_id>/delete/', views.delete_student, name='delete_student'),
    path('exam/<int:exam_id>/remove-all-students/', views.remove_all_students_from_exam, name='remove_all_students_from_exam'),
] 